// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/utilitywarehouse/terraform-applier/git (interfaces: Repositories)

// Package git is a generated GoMock package.
package git

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/utilitywarehouse/git-mirror/repository"
)

// MockRepositories is a mock of Repositories interface.
type MockRepositories struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoriesMockRecorder
}

// MockRepositoriesMockRecorder is the mock recorder for MockRepositories.
type MockRepositoriesMockRecorder struct {
	mock *MockRepositories
}

// NewMockRepositories creates a new mock instance.
func NewMockRepositories(ctrl *gomock.Controller) *MockRepositories {
	mock := &MockRepositories{ctrl: ctrl}
	mock.recorder = &MockRepositoriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositories) EXPECT() *MockRepositoriesMockRecorder {
	return m.recorder
}

// BranchCommits mocks base method.
func (m *MockRepositories) BranchCommits(arg0 context.Context, arg1, arg2 string) ([]repository.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BranchCommits", arg0, arg1, arg2)
	ret0, _ := ret[0].([]repository.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BranchCommits indicates an expected call of BranchCommits.
func (mr *MockRepositoriesMockRecorder) BranchCommits(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BranchCommits", reflect.TypeOf((*MockRepositories)(nil).BranchCommits), arg0, arg1, arg2)
}

// Clone mocks base method.
func (m *MockRepositories) Clone(arg0 context.Context, arg1, arg2, arg3 string, arg4 []string, arg5 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clone indicates an expected call of Clone.
func (mr *MockRepositoriesMockRecorder) Clone(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockRepositories)(nil).Clone), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Hash mocks base method.
func (m *MockRepositories) Hash(arg0 context.Context, arg1, arg2, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockRepositoriesMockRecorder) Hash(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockRepositories)(nil).Hash), arg0, arg1, arg2, arg3)
}

// MergeCommits mocks base method.
func (m *MockRepositories) MergeCommits(arg0 context.Context, arg1, arg2 string) ([]repository.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeCommits", arg0, arg1, arg2)
	ret0, _ := ret[0].([]repository.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergeCommits indicates an expected call of MergeCommits.
func (mr *MockRepositoriesMockRecorder) MergeCommits(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeCommits", reflect.TypeOf((*MockRepositories)(nil).MergeCommits), arg0, arg1, arg2)
}

// Mirror mocks base method.
func (m *MockRepositories) Mirror(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mirror", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mirror indicates an expected call of Mirror.
func (mr *MockRepositoriesMockRecorder) Mirror(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mirror", reflect.TypeOf((*MockRepositories)(nil).Mirror), arg0, arg1)
}

// Subject mocks base method.
func (m *MockRepositories) Subject(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subject indicates an expected call of Subject.
func (mr *MockRepositoriesMockRecorder) Subject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockRepositories)(nil).Subject), arg0, arg1, arg2)
}
