definitions:
  systems.uw.terraform-applier.v1beta1.Module:
    properties:
      spec:
        properties:
          backend:
            type: array
            x-kubernetes-patch-merge-key: name
            x-kubernetes-patch-strategy: merge
          env:
            type: array
            x-kubernetes-patch-merge-key: name
            x-kubernetes-patch-strategy: merge
          rbac:
            items:
              properties:
                role:
                  type: string
                subjects:
                  type: array
                  x-kubernetes-patch-merge-key: name
                  x-kubernetes-patch-strategy: merge
              type: object
            type: array
            x-kubernetes-patch-merge-key: role
            x-kubernetes-patch-strategy: merge
          var:
            type: array
            x-kubernetes-patch-merge-key: name
            x-kubernetes-patch-strategy: merge
        type: object
    type: object
    x-kubernetes-group-version-kind:
      - group: terraform-applier.uw.systems
        kind: Module
        version: v1beta1
