apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  #  - github.com/utilitywarehouse/terraform-applier//manifests/base
resources:
  - terraform-applier-ingress.yaml
patchesStrategicMerge:
  - terraform-applier-patch.yaml
configMapGenerator:
  - name: module1
    files:
      - main.tf=resources/module1.tf
  - name: module2
    files:
      - main.tf=resources/module2.tf
