apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraform-applier
spec:
  template:
    spec:
      containers:
        - name: terraform-applier
          env:
            # Variables depend on what terraform providers and resources you use
            #
            # For instance, the environment variables below configure the
            # Kubernetes secret backend to use the in cluster config and the
            # same namespace the terraform-applier pod is in.
            - name: KUBE_IN_CLUSTER_CONFIG
              value: "true"
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: module1
              mountPath: "/src/module1"
            - name: module2
              mountPath: "/src/module2"
      volumes:
        - name: module1
          configMap:
            name: module1-terraform
        - name: module2
          configMap:
            name: module2-terraform

