apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: terraform-applier
  name: terraform-applier
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: terraform-applier
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: terraform-applier
    spec:
      securityContext:
        # This GID is added to each container to share folder and
        # read mounted secrets
        fsGroup: 101
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: terraform-applier
      terminationGracePeriodSeconds: 300
      containers:
        - name: manager
          command:
            - /manager
          args:
            - --leader-elect
            - --termination-grace-period=240
          image: quay.io/utilitywarehouse/terraform-applier:master
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 0m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /src
              name: git-repo
              readOnly: true
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.3
          env:
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "5"
            - name: GIT_SYNC_WAIT
              value: "30"
          volumeMounts:
            - name: git-repo
              mountPath: /tmp/git
            - name: git-secret
              mountPath: /etc/git-secret
          resources:
            requests:
              cpu: 40m
              memory: 48Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-sync
            defaultMode: 0440
