apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-applier-redis
data:
  redis.conf: |
    #  setup Key event notifications for 'String' commands
    #  K  Keyspace events, published with __keyspace@<db>__ prefix.
    #  E  Keyevent events, published with __keyevent@<db>__ prefix.
    #  $  String commands
    notify-keyspace-events E$
---
apiVersion: v1
kind: Service
metadata:
  name: terraform-applier-redis
  labels:
    app: terraform-applier-redis
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app: terraform-applier-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraform-applier-redis
spec:
  replicas: 1
  serviceName: terraform-applier-redis
  selector:
    matchLabels:
      app: terraform-applier-redis
  template:
    metadata:
      labels:
        app: terraform-applier-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - "/config/redis.conf"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: terraform-applier-redis-data
              mountPath: /data
            - name: config
              mountPath: /config
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 0
              memory: 0
      volumes:
        - name: config
          configMap:
            name: terraform-applier-redis
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: terraform-applier-redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
