apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  name: terraform-applier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-applier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terraform-applier
subjects:
  - kind: ServiceAccount
    name: terraform-applier
