apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8081"
  name: terraform-applier
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: webhook
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    control-plane: terraform-applier
