apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraform-applier
spec:
  template:
    spec:
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.0
          securityContext:
            runAsUser: 65533 # git-sync user
            runAsGroup: 0 # root group to read mounted Secrets
          env:
            - name: GIT_SYNC_DEST
              value: "modules"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "5"
            - name: GIT_SYNC_WAIT
              value: "30"
          volumeMounts:
            - name: git-repo
              mountPath: /tmp/git
            - name: git-secret
              mountPath: /etc/git-secret
          resources:
            requests:
              cpu: 40m
              memory: 48Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: terraform-applier
          volumeMounts:
            - name: git-repo
              mountPath: /src
              readOnly: true
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-sync
            defaultMode: 0440
