apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-applier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform-applier
rules:
  # Used by terraform-applier to store state in secrets, leases are used to
  # perform locking
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch", "list"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "patch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terraform-applier
roleRef:
  kind: Role
  name: terraform-applier
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: terraform-applier
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
  name: terraform-applier
  labels:
    app: terraform-applier
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: terraform-applier
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraform-applier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform-applier
  serviceName: terraform-applier
  template:
    metadata:
      labels:
        app: terraform-applier
    spec:
      serviceAccountName: terraform-applier
      containers:
        - name: terraform-applier
          image: quay.io/utilitywarehouse/terraform-applier:v1
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 8080
          env:
            - name: MODULES_PATH
              value: /src
          volumeMounts:
            - name: git-repo
              mountPath: /src
              readOnly: true
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.5
          securityContext:
            runAsUser: 65533 # git-sync user
            runAsGroup: 0 # root group to read mounted Secrets
          env:
            - name: GIT_SYNC_DEST
              value: "modules"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "5"
            - name: GIT_SYNC_WAIT
              value: "30"
          volumeMounts:
            - name: git-repo
              mountPath: /tmp/git
            - name: git-secret
              mountPath: /etc/git-secret
          resources:
            requests:
              cpu: 40m
              memory: 48Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-sync
            defaultMode: 0440
