apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-applier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terraform-applier
subjects:
  - kind: ServiceAccount
    name: terraform-applier
    namespace: terraform-applier
