apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/
  #  - github.com/utilitywarehouse/terraform-applier//manifests/base?ref=0.2.0
resources:
  - terraform-applier-ingress.yaml
patchesStrategicMerge:
  - terraform-applier-patch.yaml
secretGenerator:
  # Needed by git-sync to clone repositories
  - name: git-sync
    type: Opaque
    files:
      - ssh=secrets/git-sync-ssh-key
      - known_hosts=resources/git-sync-known_hosts
  # Used by terraform-applier. Will differ based on terraform resources being applied
  # Example for the AWS provider and for a custom resource secret
  - name: terraform-applier
    type: Opaque
    files:
      - terraform-aws-provider-secret=secrets/terraform-applier-terraform-aws-provider-secret
      - example-app-s3-reader-secret=secrets/terraform-applier-example-app-s3-reader-secret
