apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-applier
spec:
  template:
    spec:
      containers:
        - name: git-sync
          env:
            - name: GIT_SYNC_REPO
              value: "git@github.com:org/repo.git"
        - name: terraform-applier
          env:
            # terraform-applier vars
            - name: REPO_PATH
              value: "/src/modules/example-env"
            - name: REPO_PATH_FILTERS
              value: "my-module-1,my-module-2,env-*"
            - name: DIFF_URL_FORMAT
              value: "https://github.com/org/repo/commit/%s"
            #
            # Variables from now depend on what terraform providers and resources you use
            # Substitue above configuration for your particular needs
            #
            # terraform-provider-aws vars
            - name: AWS_ACCESS_KEY_ID
              value: "AAAAAAAAAAAAAAAAAAAA"
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: terraform-applier
                  key: terraform-aws-provider-secret
            # custom terraform resources vars
            - name: TF_VAR_s3_reader_access_key_id
              value: "AAAAAAAAAAAAAAAAAAAA"
            - name: TF_VAR_s3_reader_secret_access_key
              valueFrom:
                secretKeyRef:
                  name: terraform-applier
                  key: example-app-s3-reader-secret
