// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/utilitywarehouse/terraform-applier/vault (interfaces: AWSSecretsEngineInterface)

// Package vault is a generated GoMock package.
package vault

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1beta1 "github.com/utilitywarehouse/terraform-applier/api/v1beta1"
)

// MockAWSSecretsEngineInterface is a mock of AWSSecretsEngineInterface interface.
type MockAWSSecretsEngineInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSSecretsEngineInterfaceMockRecorder
}

// MockAWSSecretsEngineInterfaceMockRecorder is the mock recorder for MockAWSSecretsEngineInterface.
type MockAWSSecretsEngineInterfaceMockRecorder struct {
	mock *MockAWSSecretsEngineInterface
}

// NewMockAWSSecretsEngineInterface creates a new mock instance.
func NewMockAWSSecretsEngineInterface(ctrl *gomock.Controller) *MockAWSSecretsEngineInterface {
	mock := &MockAWSSecretsEngineInterface{ctrl: ctrl}
	mock.recorder = &MockAWSSecretsEngineInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSSecretsEngineInterface) EXPECT() *MockAWSSecretsEngineInterfaceMockRecorder {
	return m.recorder
}

// GenerateCreds mocks base method.
func (m *MockAWSSecretsEngineInterface) GenerateCreds(arg0 string, arg1 *v1beta1.VaultAWSRequest) (*AWSCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCreds", arg0, arg1)
	ret0, _ := ret[0].(*AWSCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCreds indicates an expected call of GenerateCreds.
func (mr *MockAWSSecretsEngineInterfaceMockRecorder) GenerateCreds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCreds", reflect.TypeOf((*MockAWSSecretsEngineInterface)(nil).GenerateCreds), arg0, arg1)
}
