// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/utilitywarehouse/terraform-applier/vault (interfaces: ProviderInterface)

// Package vault is a generated GoMock package.
package vault

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1beta1 "github.com/utilitywarehouse/terraform-applier/api/v1beta1"
)

// MockProviderInterface is a mock of ProviderInterface interface.
type MockProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProviderInterfaceMockRecorder
}

// MockProviderInterfaceMockRecorder is the mock recorder for MockProviderInterface.
type MockProviderInterfaceMockRecorder struct {
	mock *MockProviderInterface
}

// NewMockProviderInterface creates a new mock instance.
func NewMockProviderInterface(ctrl *gomock.Controller) *MockProviderInterface {
	mock := &MockProviderInterface{ctrl: ctrl}
	mock.recorder = &MockProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderInterface) EXPECT() *MockProviderInterfaceMockRecorder {
	return m.recorder
}

// GenerateAWSCreds mocks base method.
func (m *MockProviderInterface) GenerateAWSCreds(arg0 string, arg1 *v1beta1.VaultAWSRequest) (*AWSCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAWSCreds", arg0, arg1)
	ret0, _ := ret[0].(*AWSCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAWSCreds indicates an expected call of GenerateAWSCreds.
func (mr *MockProviderInterfaceMockRecorder) GenerateAWSCreds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAWSCreds", reflect.TypeOf((*MockProviderInterface)(nil).GenerateAWSCreds), arg0, arg1)
}
